---
- name: install mysql
  yum: name=mysql state=present
  yum: name=mysql-server state=present
- name: write mysql config file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mysql
- name: ensure mysql is running
  service: name=mysqld enabled=yes state=started
- name: install MySQL-python
  yum: name=MySQL-python state=present
- name: create mysql database
  mysql_db: name=mt state=present
- name: create mysql user
  mysql_user: name=mt login_user=mt password={{ mysql_password }} priv=mt.*:ALL login_user=root login_password={{ mysql_root_password }}
